### ISSUE TITLE
ARCHIVIZ PLUGIN IS NOT VALID

### ISSUE THREAD

**Issue by CCicc21** [BCWrit/OmekaArchiviz#1]
![Screenshot 2024-06-24 155706](https://github.com/BCWrit/OmekaArchiviz/assets/160035508/9910cee6-d874-441b-991a-7b04daf9f38c)
I AM TRYING TO INSTALL THIS PLUGIN BUT I CAN'T UNDERSTAND WHAT THE PROBLEM IS... I HAVE INSTALLED OMEKA CLASSIC ON WINDOWS 11 LOCALLY USING LARAGON

**Comment by zhangyilibecnu** [comment]
I also encountered the same error. Is the root directory of the plugin missing a *.php file?
![screenshot-1724227359449](https://github.com/user-attachments/assets/574e9eb8-aca1-47a3-80f5-f322bfb45729)

**Comment by BCWrit** [comment]
Hi, yes, this is likely because the plug-in is actually a collection of 4 plug-ins, so the php files are in those directories. Added a step to the readme to move everything up one level in the directory structure to be in /readme. This should at least address this issue. The install is pretty complex: I'd suggest working with your local IT professional if at all possible!
